name: 'Notion create page from markdown file'
description: 'Creates a new page in an existing database to capture content of a markdown file'
branding:
  icon: type
  color: green
inputs:
  token:
    description: 'Notion API token'
    required: true    
  database:
    description: 'Parent database to add to'
    required: true    
  name:  
    description: 'Name for the release'
    required: true
  filepath:  
    description: 'The path to the file to add to Notion' 
    required: true
outputs:
  status: 
    description: 'The status of the update'
runs:
  using: 'node18'
  main: 'dist/index.js'