name: Test Notion

on: 
    workflow_dispatch

jobs:
    notion: 
        runs-on: ubuntu-latest
        steps:
            - name: Notion release notes        
              uses: jlpdeveloper/notion-markdown-creator@947cbf6b19f92a5d984d6a8d006f632bb16ce531
              with:          
                token: ${{ secrets.NOTION_TOKEN }}
                database: ${{ secrets.NOTION_DATABASE }}
                name: Super Amazing Service    
                filepath: './test.md'